data:
  raw: "data/raw/raw_data.csv"
  processed: "data/processed/"
  train: "data/processed/train_data_gold.csv"
  test:
    X: "data/processed/X_test.csv"
    y: "data/processed/y_test.csv"
  interim: "data/interim/"
  external: "data/external/"
  dvc_remote: "github"

models:
  dir: "models/"

mlflow:
  tracking_uri: "mlruns"
